// ============================================================
//  MARKETING DASHBOARD DATA
//  This is the only file you need to edit.
//  Find the vehicle name, update the text, save the file.
// ============================================================

const VEHICLES = [
  "144\" MODEs",
  "CREW MODE",
  "TOUR MODE",
  "GXV WILD",
  "GXV HILT",
  "GXV EPIC",
  "Grand Bohemian",
];

const PILLARS = [
  {
    id: "dealer",
    name: "Dealer Channels",
    color: "#1a56a0",
    bg: "#e8f0fb",
    tactics: [
      {
        id: "showroom",
        name: "Showroom & Office Visual Merchandising",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "promo-materials",
        name: "Promotional Materials",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "sales-show",
        name: "Sales / Show Support",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "geofencing",
        name: "Geo Fencing / Local / Targeted Campaigns",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
    ],
  },
  {
    id: "community",
    name: "Community",
    color: "#2d7a3a",
    bg: "#e6f4e8",
    tactics: [
      {
        id: "app",
        name: "App",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "tour",
        name: "Tour",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "experiences",
        name: "Experiences",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "activations",
        name: "Activations",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "blogs",
        name: "Blogs",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
    ],
  },
  {
    id: "sales",
    name: "Sales Support",
    color: "#7a4a0a",
    bg: "#faf0e0",
    tactics: [
      {
        id: "digital-marketing",
        name: "Integrated Digital Marketing & Demand Gen",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "campaigns",
        name: "Campaigns (Email / Digital)",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "promotions",
        name: "Promotions",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
    ],
  },
  {
    id: "brand",
    name: "Brand Experience",
    color: "#0f6e56",
    bg: "#e0f4ee",
    tactics: [
      {
        id: "web",
        name: "Web",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "meta",
        name: "Social — Meta / Facebook",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "tiktok",
        name: "Social — TikTok",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "linkedin",
        name: "Social — LinkedIn",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "youtube",
        name: "Social — YouTube",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "search",
        name: "Search / AI",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
    ],
  },
  {
    id: "pr",
    name: "PR / Media",
    color: "#8c2d50",
    bg: "#f9e8ef",
    tactics: [
      {
        id: "print",
        name: "Print (Paid & Earned)",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "influencers",
        name: "Influencers",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "press",
        name: "Press & Media",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
      {
        id: "brand-moments",
        name: "Brand Moments & Product",
        vehicles: {
          '144" MODEs': "Placeholder — describe what's happening for this vehicle here.",
          "CREW MODE": "Placeholder — describe what's happening for this vehicle here.",
          "TOUR MODE": "Placeholder — describe what's happening for this vehicle here.",
          "GXV WILD": "Placeholder — describe what's happening for this vehicle here.",
          "GXV HILT": "Placeholder — describe what's happening for this vehicle here.",
          "GXV EPIC": "Placeholder — describe what's happening for this vehicle here.",
          "Grand Bohemian": "Placeholder — describe what's happening for this vehicle here.",
        },
      },
    ],
  },
];

export { VEHICLES, PILLARS };
